[project]
name = "polarcli-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyfiglet>=1.0.4",
    "typer>=0.23.0",
]
